# Flecha original usando múltiples print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")


# 🔹 Versión optimizada (menos print usando \n)
print("\n--- Flecha con un solo print ---\n")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")


# 🔹 Flecha el doble de grande (manteniendo proporción)
print("\n--- Flecha doble tamaño ---\n")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("******     ******")
print("   *           *")
print("   *           *")
print("   *           *")
print("   *************")


# 🔹 Flecha duplicada (dos flechas lado a lado)
print("\n--- Flecha duplicada ---\n")
print("    *    " * 2)
print("   * *   " * 2)
print("  *   *  " * 2)
print(" *     * " * 2)
print("***   ***" * 2)
print("  *   *  " * 2)
print("  *   *  " * 2)
print("  *****  " * 2)